// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZJPSP0gybYAXVQv5YaCjpLweG_Q2J5L0',
    appId: '1:688115994114:web:f60ad0f46bbbbe0ecc611b',
    messagingSenderId: '688115994114',
    projectId: 'bill-manager-app-db002',
    authDomain: 'bill-manager-app-db002.firebaseapp.com',
    storageBucket: 'bill-manager-app-db002.firebasestorage.app',
    measurementId: 'G-5DJK4JC5K4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwBGBs_GioJ1_JSaUyYGRYNTbLudmY9z8',
    appId: '1:688115994114:android:4cf4bc2ea4fd59cfcc611b',
    messagingSenderId: '688115994114',
    projectId: 'bill-manager-app-db002',
    storageBucket: 'bill-manager-app-db002.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCieSW_mVHvBd057AdLjdfEDGh0FsLeiO8',
    appId: '1:688115994114:ios:4922b7af6ceac587cc611b',
    messagingSenderId: '688115994114',
    projectId: 'bill-manager-app-db002',
    storageBucket: 'bill-manager-app-db002.firebasestorage.app',
    iosClientId: '688115994114-tm1343ons5gki1lmqbvrfhe0tbg6u3rs.apps.googleusercontent.com',
    iosBundleId: 'com.example.billManagerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCieSW_mVHvBd057AdLjdfEDGh0FsLeiO8',
    appId: '1:688115994114:ios:4922b7af6ceac587cc611b',
    messagingSenderId: '688115994114',
    projectId: 'bill-manager-app-db002',
    storageBucket: 'bill-manager-app-db002.firebasestorage.app',
    iosClientId: '688115994114-tm1343ons5gki1lmqbvrfhe0tbg6u3rs.apps.googleusercontent.com',
    iosBundleId: 'com.example.billManagerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZJPSP0gybYAXVQv5YaCjpLweG_Q2J5L0',
    appId: '1:688115994114:web:ad7edba4b6df8ec5cc611b',
    messagingSenderId: '688115994114',
    projectId: 'bill-manager-app-db002',
    authDomain: 'bill-manager-app-db002.firebaseapp.com',
    storageBucket: 'bill-manager-app-db002.firebasestorage.app',
    measurementId: 'G-MJ5G4H07D6',
  );
}
